#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <dweller/symbols.h>

#define DW_SYMCASE_GENERIC(STRING) if (strlen(STRING) > maxsize) { maxsize = strlen(STRING); maxstr = STRING; }

#define DW_SYMCASE_AT(NAME, VALUE)         DW_SYMCASE_GENERIC("DW_AT_"         #NAME)
#define DW_SYMCASE_LANG(NAME, VALUE)       DW_SYMCASE_GENERIC("DW_LANG_"       #NAME)
#define DW_SYMCASE_TAG(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_TAG_"        #NAME)
#define DW_SYMCASE_ORD(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_ORD_"        #NAME)
#define DW_SYMCASE_ACCESS(NAME, VALUE)     DW_SYMCASE_GENERIC("DW_ACCESS_"     #NAME)
#define DW_SYMCASE_ATE(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_ATE_"        #NAME)
#define DW_SYMCASE_CC(NAME, VALUE)         DW_SYMCASE_GENERIC("DW_CC_"         #NAME)
#define DW_SYMCASE_CFA(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_CFA_"        #NAME)
#define DW_SYMCASE_CHILDREN(NAME, VALUE)   DW_SYMCASE_GENERIC("DW_CHILDREN_"   #NAME)
#define DW_SYMCASE_DSC(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_DSC_"        #NAME)
#define DW_SYMCASE_FORM(NAME, VALUE)       DW_SYMCASE_GENERIC("DW_FORM_"       #NAME)
#define DW_SYMCASE_ID(NAME, VALUE)         DW_SYMCASE_GENERIC("DW_ID_"         #NAME)
#define DW_SYMCASE_INL(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_INL_"        #NAME)
#define DW_SYMCASE_LNE(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_LNE_"        #NAME)
#define DW_SYMCASE_LNS(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_LNS_"        #NAME)
#define DW_SYMCASE_MACINFO(NAME, VALUE)    DW_SYMCASE_GENERIC("DW_MACINFO_"    #NAME)
#define DW_SYMCASE_OP(NAME, VALUE)         DW_SYMCASE_GENERIC("DW_OP_"         #NAME)
#define DW_SYMCASE_VIRTUALITY(NAME, VALUE) DW_SYMCASE_GENERIC("DW_VIRTUALITY_" #NAME)
#define DW_SYMCASE_VIS(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_VIS_"        #NAME)
#define DW_SYMCASE_DS(NAME, VALUE)         DW_SYMCASE_GENERIC("DW_DS_"         #NAME)
#define DW_SYMCASE_END(NAME, VALUE)        DW_SYMCASE_GENERIC("DW_END_"        #NAME)
#define DW_SYMCASE_UT(NAME, VALUE)         DW_SYMCASE_GENERIC("DW_UT_"         #NAME)

#define DW_SYMNSCASE(NAME) DW_##NAME##_SYMBOLS(DW_SYMCASE_##NAME)

int main(void)
{
    const char *maxstr = "";
    size_t maxsize = 0;

    DW_SYMNSCASE(AT)
    DW_SYMNSCASE(LANG)
    DW_SYMNSCASE(TAG)
    DW_SYMNSCASE(ORD)
    DW_SYMNSCASE(ACCESS)
    DW_SYMNSCASE(ATE)
    DW_SYMNSCASE(CC)
    DW_SYMNSCASE(CFA)
    DW_SYMNSCASE(CHILDREN)
    DW_SYMNSCASE(DSC)
    DW_SYMNSCASE(FORM)
    DW_SYMNSCASE(ID)
    DW_SYMNSCASE(INL)
    DW_SYMNSCASE(LNE)
    DW_SYMNSCASE(LNS)
    DW_SYMNSCASE(MACINFO)
    DW_SYMNSCASE(OP)
    DW_SYMNSCASE(VIRTUALITY)
    DW_SYMNSCASE(VIS)
    DW_SYMNSCASE(DS)
    DW_SYMNSCASE(END)
    DW_SYMNSCASE(UT)

    printf("Maximum symbol size is: %zu (%s)\n", maxsize, maxstr);

    return 0;
}
